name: Build WireGuard for armv7

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [arm, armv7]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev libelf-dev libmnl-dev

    - name: Compile WireGuard
      run: make ARCH=${{ matrix.target }} CROSS_COMPILE=arm-linux-gnueabihf-

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wireguard-armv7
        path: ./wireguard.ko
