name: Build WireGuard for armv7

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libmnl-dev
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build WireGuard
      run: |
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- modules
